# Generated by Django 3.1.4 on 2021-01-08 18:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='CODE')),
                ('name', models.CharField(max_length=15, verbose_name='NAME')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='DATE')),
                ('title', models.CharField(max_length=100, verbose_name='TITLE')),
                ('content', models.TextField(blank=True, verbose_name='CONTENT')),
                ('publisher', models.CharField(max_length=8, verbose_name='PUBLISHER')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='CODE')),
                ('name', models.CharField(max_length=20, verbose_name='NAME')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('data_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='DATE')),
                ('sise', models.PositiveIntegerField(verbose_name='SISE')),
                ('amount', models.PositiveBigIntegerField(verbose_name='AMOUNT')),
                ('code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='homeapp.stockinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('data_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='DATE')),
                ('sise', models.PositiveIntegerField(verbose_name='SISE')),
                ('amount', models.FloatField(verbose_name='AMOUNT')),
                ('code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coin', to='homeapp.coininfo')),
            ],
        ),
    ]
