# Generated by Django 3.1.4 on 2021-01-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_auto_20210108_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='data_id',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='data_id',
        ),
        migrations.AddField(
            model_name='coin',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
