# Generated by Django 3.1.4 on 2021-01-12 22:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='DATE')),
                ('iore', models.BooleanField(verbose_name='IORE')),
                ('big_category', models.SmallIntegerField(blank=True, null=True, verbose_name='BIG_CATEGORY')),
                ('mid_category', models.SmallIntegerField(blank=True, null=True, verbose_name='MID_CATEGORY')),
                ('sma_category', models.SmallIntegerField(blank=True, null=True, verbose_name='SMA_CATEGORY')),
                ('memo', models.CharField(blank=True, max_length=255, verbose_name='MEMO')),
                ('amount', models.PositiveBigIntegerField(verbose_name='AMOUNT')),
            ],
        ),
    ]
