# Generated by Django 3.1.4 on 2021-01-13 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_accounting_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='big_category',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='BIG_CATEGORY'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='DATE'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='mid_category',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='MID_CATEGORY'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='sma_category',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='SMA_CATEGORY'),
        ),
    ]
