# Generated by Django 3.1.4 on 2021-01-04 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='DATE')),
                ('code', models.CharField(max_length=3, verbose_name='CODE')),
                ('name', models.CharField(max_length=15, verbose_name='NAME')),
                ('sise', models.PositiveIntegerField(verbose_name='SISE')),
                ('amount', models.PositiveBigIntegerField(verbose_name='AMOUNT')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='DATE')),
                ('title', models.CharField(max_length=100, verbose_name='TITLE')),
                ('content', models.TextField(blank=True, verbose_name='CONTENT')),
                ('writer', models.CharField(max_length=12, verbose_name='WRITER')),
                ('publisher', models.CharField(max_length=8, verbose_name='PUBLISHER')),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='DATE')),
                ('code', models.CharField(max_length=6, verbose_name='CODE')),
                ('name', models.CharField(max_length=20, verbose_name='NAME')),
                ('sise', models.PositiveIntegerField(verbose_name='SISE')),
                ('amount', models.PositiveBigIntegerField(verbose_name='AMOUNT')),
            ],
        ),
    ]
