# Generated by Django 3.1.4 on 2021-01-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_news_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='amount',
            field=models.FloatField(verbose_name='AMOUNT'),
        ),
    ]
