# Generated by Django 3.1.4 on 2021-01-07 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='DATE')),
                ('freedps', models.IntegerField(blank=True, verbose_name='FREEDPS')),
                ('stock', models.IntegerField(blank=True, verbose_name='STOCK')),
                ('installment', models.IntegerField(blank=True, verbose_name='INSTALLMENT')),
                ('house_sbsc', models.IntegerField(blank=True, verbose_name='HOUSE_SBSC')),
                ('cma', models.IntegerField(blank=True, verbose_name='CMA')),
                ('invest', models.IntegerField(blank=True, verbose_name='INVEST')),
                ('house', models.IntegerField(blank=True, verbose_name='HOUSE')),
                ('debt', models.IntegerField(blank=True, verbose_name='DEPT')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_asset', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
