# Generated by Django 3.1.4 on 2021-01-07 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assetapp', '0002_auto_20210107_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='cma',
            field=models.IntegerField(blank=True, null=True, verbose_name='CMA'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='debt',
            field=models.IntegerField(blank=True, null=True, verbose_name='DEPT'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='freedps',
            field=models.IntegerField(blank=True, null=True, verbose_name='FREEDPS'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='house',
            field=models.IntegerField(blank=True, null=True, verbose_name='HOUSE'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='house_sbsc',
            field=models.IntegerField(blank=True, null=True, verbose_name='HOUSE_SBSC'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='installment',
            field=models.IntegerField(blank=True, null=True, verbose_name='INSTALLMENT'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='invest',
            field=models.IntegerField(blank=True, null=True, verbose_name='INVEST'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='STOCK'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
