# Generated by Django 3.1.4 on 2021-01-04 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100, verbose_name='USERID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='DATE')),
                ('freedps', models.IntegerField(blank=True, verbose_name='FREEDPS')),
                ('stock', models.IntegerField(blank=True, verbose_name='STOCK')),
                ('installment', models.IntegerField(blank=True, verbose_name='INSTALLMENT')),
                ('house_sbsc', models.IntegerField(blank=True, verbose_name='HOUSE_SBSC')),
                ('cma', models.IntegerField(blank=True, verbose_name='CMA')),
                ('invest', models.IntegerField(blank=True, verbose_name='INVEST')),
                ('house', models.IntegerField(blank=True, verbose_name='HOUSE')),
                ('debt', models.IntegerField(blank=True, verbose_name='DEPT')),
            ],
        ),
    ]
